package HelloWorldApp;

/**
* HelloWorldApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* jeudi 23 octobre 2025 21 h 54 CEST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorldApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (HelloWorldApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorldApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorldApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorldApp.HelloHelper.type ();
  }

}
