package HelloWorldApp;


/**
* HelloWorldApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* jeudi 23 octobre 2025 21 h 54 CEST
*/

public interface HelloOperations 
{
  String HelloMessage ();
  void HelloMessage (String newHelloMessage);
} // interface HelloOperations
